-- Kiểm thử riêng, không thay đổi CSDL payflow_db hiện có.
-- Chạy trên CSDL demo mới. Script chỉ nhập dữ liệu một lần.
CREATE DATABASE IF NOT EXISTS payflow_demo;
USE payflow_demo;
CREATE TABLE Transactions (
    transaction_id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT,
    amount DECIMAL(15,2),
    transaction_type VARCHAR(20),
    created_at DATETIME
) ENGINE=InnoDB;

-- Tạo 100.000 giao dịch trải trên 1.000 ngày.
INSERT INTO Transactions (user_id, amount, transaction_type, created_at)
SELECT MOD(n, 1000) + 1,
       CAST(MOD(n, 10000) + 1 AS DECIMAL(15,2)),
       CASE MOD(n, 3) WHEN 0 THEN 'DEPOSIT'
                     WHEN 1 THEN 'WITHDRAW' ELSE 'TRANSFER' END,
       DATE_ADD('2025-01-01 00:00:00', INTERVAL MOD(n, 1000) DAY)
FROM (
    SELECT a.d + 10*b.d + 100*c.d + 1000*d.d + 10000*e.d AS n
    FROM (SELECT 0 d UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a
    CROSS JOIN (SELECT 0 d UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b
    CROSS JOIN (SELECT 0 d UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c
    CROSS JOIN (SELECT 0 d UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d
    CROSS JOIN (SELECT 0 d UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) e
) numbers;

-- Kiểm thử mốc biên và NULL.
INSERT INTO Transactions (user_id, amount, transaction_type, created_at) VALUES
(1, 100.00, 'DEPOSIT', '2026-05-31 23:59:59'),
(1, 200.00, 'DEPOSIT', '2026-06-01 00:00:00'),
(1, 300.00, 'DEPOSIT', '2026-06-30 23:59:59'),
(1, 400.00, 'DEPOSIT', '2026-07-01 00:00:00'),
(1, NULL, 'DEPOSIT', '2026-06-15 00:00:00'),
(1, 500.00, 'DEPOSIT', NULL);
SELECT COUNT(*) AS total_rows FROM Transactions;
-- Kết quả phải là 100006.

-- Tiếp theo mở payflow_optimized.sql và đổi USE payflow_db;
-- thành USE payflow_demo; trước khi chạy toàn bộ script.
